MarkMode: Map # Alone, Map
ThrVal: 210 # 210 to 240
MarkHeight: 1679  # manually input
IDNum: 3  # A total number of landmarks under Map Mode
RefID: 8626 # Ref ID under map mode
ThrAlg: Auto
MarkType: Office  # home for HLDn-S / office for HLDn-L
MarkDim: 1  # 1 for HLDn-2, 2 for HLDn-3 / Q. What if we have only HLDn-1 ?
MapMode: Stop
# If map building action under Map mode is required,
# set 'Start' and start map building. or set 'Stop'

# reference:
# stargazer_publisher.py - get_options


#cf. DarkRider rpm = 200